apiVersion: v2
name: thunderdome-planning-poker
description: A Helm chart for thunderdome-planning-poker
type: application
version: 1.0.0
appVersion: "v2.29.2"
dependencies:
  - name: postgresql
    version: "12.2.6"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
