version: 1.0.6
apiVersion: v2
name: healthchecks
description: A Helm chart for Kubernetes
maintainers:
  - email: rakshit@improwised.com
    name: rakshit
type: application
appVersion: 2.7.0
sources:
  - https://github.com/healthchecks/healthchecks
dependencies:
  - name: postgresql
    version: 10.14.3
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled,global.postgresql.enabled
